#!/bin/sh

case "$1" in
    # Load scull, module driver, modprobe
    start)
        echo "Loading modules"
        cd /usr/bin
        aesdchar_load
        ;;
    stop)
        echo "Unloading modules"
        cd /usr/bin
        aesdchar_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac
